### ISSUE TITLE
Add map key

### ISSUE THREAD

**Issue by hepeb0t** [Digital-Water-Publics/Thames21-Socio-Ecological-Dashboard#12]
Add a a key to the map explaining the colour code

**Comment by natesheehan** [comment]
@hepeb0t a legend has been added to the map and the previous copy has been used. Let me know if you would like to change th copy.

**Comment by hepeb0t** [comment]
- Please replace the headline of the legend with "Sentiment Polarity Score"
- Please add the score range to the colour codes
- Need to add a sentence about what data the scores are based on: average of all tweets over 10 years?
